# Generated by Django 3.1.13 on 2022-05-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500)),
                ('client_company_name', models.CharField(blank=True, max_length=500)),
                ('client_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.IntegerField()),
                ('company_phone', models.IntegerField(blank=True)),
                ('contry', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='client logo')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('logo_image', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=5000)),
                ('project_status', models.CharField(choices=[('Estimate', 'Estimate'), ('Conform', 'Conform'), ('Cancel', 'Cancel'), ('In progress', 'In progress'), ('Done', 'Done')], default='Estimate', max_length=100)),
                ('project_billing_amount', models.BigIntegerField()),
                ('bill_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=100)),
                ('document', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('note', models.CharField(max_length=5000)),
                ('pay_image', models.ImageField(upload_to='Pay receipt')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online transfer', 'Online transfer')], max_length=200)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_whom', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('product', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.FileField(upload_to='drawings')),
                ('drawing1', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing2', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing3', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing4', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing5', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
    ]
