# Generated by Django 3.2.12 on 2022-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='logo_image',
            field=models.ImageField(default=2, upload_to='logos'),
            preserve_default=False,
        ),
    ]
