# Generated by Django 3.2.12 on 2022-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500)),
                ('client_company_name', models.CharField(blank=True, max_length=500)),
                ('client_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.IntegerField()),
                ('company_phone', models.IntegerField(blank=True)),
                ('contry', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='client logo')),
            ],
        ),
    ]
