# Generated by Django 4.0.3 on 2022-03-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=5000)),
                ('project_status', models.CharField(choices=[('Estimate', 'Estimate'), ('Conform', 'Conform'), ('Cancel', 'Cancel'), ('In progress', 'In progress'), ('Done', 'Done')], default='Estimate', max_length=100)),
                ('project_billing_amount', models.BigIntegerField()),
                ('bill_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=100)),
                ('document', models.CharField(max_length=50)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('note', models.CharField(max_length=5000)),
                ('pay_image', models.ImageField(upload_to='Pay receipt')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online transfer', 'Online transfer')], max_length=200)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.FileField(upload_to='drawings')),
                ('drawing1', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing2', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing3', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing4', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('drawing5', models.FileField(blank=True, null=True, upload_to='drawings')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
