# Generated by Django 4.0.3 on 2022-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_payment_drawings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.TextField(),
        ),
    ]
