# Generated by Django 4.0.3 on 2022-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='drawing',
            field=models.ImageField(upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing1',
            field=models.ImageField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing2',
            field=models.ImageField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing3',
            field=models.ImageField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing4',
            field=models.ImageField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing5',
            field=models.ImageField(blank=True, null=True, upload_to='drawings'),
        ),
    ]
