# Generated by Django 4.0.3 on 2022-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_drawings_drawing_alter_drawings_drawing1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='drawing',
            field=models.FileField(upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing1',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing2',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing3',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing4',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='drawing5',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
    ]
