# Generated by Django 3.1.13 on 2022-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220519_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
